// fields-of-study.tsx - Comprehensive list of educational fields of study

export const FIELDS_OF_STUDY = [
    // Traditional Academic Fields
    // Business & Management
    "Accounting",
    "Actuarial Science",
    "Business Administration",
    "Business Analytics",
    "Economics",
    "Entrepreneurship",
    "Finance",
    "Human Resource Management",
    "International Business",
    "Marketing",
    "Operations Management",
    "Organizational Leadership",
    "Project Management",
    "Real Estate",
    "Supply Chain Management",
    "Taxation",
  
    // STEM Fields
    "Aerospace Engineering",
    "Agriculture",
    "Applied Mathematics",
    "Astronomy",
    "Astrophysics",
    "Biochemistry",
    "Bioengineering",
    "Biology",
    "Biomedical Engineering",
    "Biotechnology",
    "Chemical Engineering",
    "Chemistry",
    "Civil Engineering",
    "Computer Engineering",
    "Computer Science",
    "Construction Management",
    "Cybersecurity",
    "Data Science",
    "Electrical Engineering",
    "Environmental Engineering",
    "Environmental Science",
    "Food Science",
    "Forestry",
    "Game Development",
    "Genetics",
    "Geographic Information Systems (GIS)",
    "Geology",
    "Industrial Engineering",
    "Information Systems",
    "Information Technology",
    "Marine Biology",
    "Materials Science",
    "Mathematics",
    "Mechanical Engineering",
    "Meteorology",
    "Microbiology",
    "Mining Engineering",
    "Nanotechnology",
    "Nuclear Engineering",
    "Petroleum Engineering",
    "Physics",
    "Robotics",
    "Software Engineering",
    "Statistics",
    "Systems Engineering",
    "Web Development",
    "Wildlife Biology",
  
    // Healthcare & Medicine
    "Athletic Training",
    "Audiology",
    "Clinical Laboratory Science",
    "Dental Hygiene",
    "Dentistry",
    "Diagnostic Medical Sonography",
    "Dietetics",
    "Emergency Medical Services (EMS)",
    "Exercise Science",
    "Health Administration",
    "Health Informatics",
    "Health Sciences",
    "Healthcare Management",
    "Kinesiology",
    "Medical Assisting",
    "Medical Imaging",
    "Medicine",
    "Nursing",
    "Nutrition",
    "Occupational Therapy",
    "Optometry",
    "Pharmacy",
    "Physical Therapy",
    "Physician Assistant Studies",
    "Public Health",
    "Radiation Therapy",
    "Radiologic Technology",
    "Respiratory Therapy",
    "Speech-Language Pathology",
    "Sports Medicine",
    "Surgical Technology",
    "Veterinary Medicine",
    "Veterinary Technology",
  
    // Social Sciences & Humanities
    "Anthropology",
    "Archaeology",
    "Art History",
    "Classical Studies",
    "Communications",
    "Comparative Literature",
    "Conflict Resolution",
    "Creative Writing",
    "Criminal Justice",
    "Criminology",
    "Digital Humanities",
    "English",
    "Environmental Studies",
    "Ethnic Studies",
    "Foreign Languages",
    "Gender Studies",
    "Geography",
    "History",
    "Human Services",
    "International Relations",
    "Journalism",
    "Legal Studies",
    "Liberal Arts",
    "Library Science",
    "Linguistics",
    "Literature",
    "Media Studies",
    "Museum Studies",
    "Philosophy",
    "Political Science",
    "Psychology",
    "Public Administration",
    "Public Policy",
    "Religious Studies",
    "Social Work",
    "Sociology",
    "Theology",
    "Urban Planning",
    "Women's Studies",
  
    // Arts & Design
    "Acting",
    "Animation",
    "Architecture",
    "Art",
    "Ceramics",
    "Creative Arts",
    "Dance",
    "Design",
    "Digital Media",
    "Fashion Design",
    "Film Production",
    "Fine Arts",
    "Graphic Design",
    "Industrial Design",
    "Interior Design",
    "Landscape Architecture",
    "Music",
    "Music Production",
    "Painting",
    "Photography",
    "Sculpture",
    "Studio Art",
    "Theater",
    "Visual Arts",
  
    // Education
    "Adult Education",
    "Curriculum and Instruction",
    "Early Childhood Education",
    "Educational Leadership",
    "Educational Psychology",
    "Educational Technology",
    "Elementary Education",
    "Higher Education",
    "Instructional Design",
    "Physical Education",
    "School Counseling",
    "Secondary Education",
    "Special Education",
    "Teaching English as a Second Language (TESOL)",
  
    // Law & Legal
    "Criminal Justice",
    "Criminology",
    "Forensic Science",
    "Justice Studies",
    "Law",
    "Legal Studies",
    "Paralegal Studies",
    "Pre-Law",
  
    // Trades & Vocational Training
    "HVAC (Heating, Ventilation, and Air Conditioning)",
    "Automotive Technology",
    "Aviation Maintenance",
    "Barbering",
    "Building Construction",
    "Carpentry",
    "Commercial Driving",
    "Cosmetology",
    "Culinary Arts",
    "Diesel Technology",
    "Electrical Technology",
    "Electronics",
    "Esthetics",
    "Firefighting",
    "Heavy Equipment Operation",
    "Hospitality Management",
    "Industrial Maintenance",
    "Machining",
    "Marine Mechanics",
    "Massage Therapy",
    "Mechanics",
    "Medical Assistant",
    "Motorcycle Mechanics",
    "Plumbing",
    "Practical Nursing",
    "Precision Production",
    "Refrigeration Technology",
    "Tool and Die Making",
    "Welding",
    "Wind Energy Technology",
  
    // Military & Defense
    "Aeronautics",
    "Cybersecurity",
    "Defense Studies",
    "Military Science",
    "National Security",
    "Naval Science",
  
    // Specialized & Emerging Fields
    "Artificial Intelligence",
    "Blockchain Technology",
    "Cannabis Studies",
    "Cloud Computing",
    "Drone Technology",
    "E-commerce",
    "Ethical Hacking",
    "FinTech (Financial Technology)",
    "Machine Learning",
    "Quantum Computing",
    "Renewable Energy",
    "Robotics",
    "Social Media Management",
    "Sustainable Development",
    "User Experience (UX) Design",
    "Virtual Reality",
  
    // Certificates & Professional Programs
    "Bookkeeping",
    "Clinical Medical Assistant",
    "Commercial Pilot",
    "Digital Marketing",
    "Emergency Medical Technician (EMT)",
    "Financial Planning",
    "First Responder",
    "Fitness Training",
    "Human Resources Management",
    "Mortgage Banking",
    "Nonprofit Management",
    "Paralegal",
    "Phlebotomy",
    "Project Management",
    "Real Estate",
    "Scrum Master",
    "Six Sigma",
    "Tax Preparation",
    "Teaching English as a Foreign Language (TEFL)",
    "Technical Writing",
  
    // Other Fields
    "Interdisciplinary Studies",
    "General Studies",
    "Undecided",
    "Other"
  ];
  
  export default FIELDS_OF_STUDY;